#!/bin/bash

# Set arguments
PORT=8080
BUFFSIZE=100

# Build and compile all files
make dataserver

# If compilation is successful, run client
if [[ $? -eq 0 ]]; then
    ./dataserver -b $BUFFSIZE -p $PORT
fi
